Food   = input('Enter a type of food: ')
Name   = input('Enter a girls name: ')
Adj    = input('Enter the adj:')
Noun   = input('Enter the noun: ')
Verb1  = input('Enter the verb in past tense:')
Verb2  = input('Enter the verb in past tense:')
Verb3  = input('Enter the verb in past tense:')
Noun1  = input('Enter a noun: ')

print('It was'+' '+ Food)
print('day at school,and'+' '+Name)
print( 'was super'+' '+ Adj+' '+'for lunch')
print('But when she went outside to eat,a'+' '+Noun+' '+'stole her')
print(Food+' '+'!'+' '+Name+' '+'chased the')
print(Noun+' '+'all over school.She'+' '+Verb1 +' '+ ',' +' '+ Verb2 +',and' +' '+Verb3)
print( 'through the playground.Then she tripped on her' +' '+ Noun1 +' '+ 'and the' +' '+ Noun +' '+ 'escaped!Luckily,')
print(Name+' '+ 's friends were willing to share their'+' '+ Food+' '+ 'with her.')
